name: Deploy

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.0'  # 确保这个版本与您的项目兼容

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # 选择一个合适的 Node.js 版本

    - name: Enable bundler cache
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Install dependencies
      run: |
        gem update --system
        gem install bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        npm install -g mermaid.cli

    - name: Setup deploy options
      id: setup
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        if [[ ${{ github.event_name }} == 'pull_request' ]]; then
          echo "::set-output name=SRC_BRANCH::${{ github.head_ref }}"
          echo "::set-output name=NO_PUSH::--no-push"
        else
          echo "::set-output name=SRC_BRANCH::${{ github.ref_name }}"
        fi
        echo "::set-output name=DEPLOY_BRANCH::gh-pages"

    - name: Deploy website
      run: |
        bash bin/deploy --verbose ${{ steps.setup.outputs.NO_PUSH }}
                        --src ${{ steps.setup.outputs.SRC_BRANCH }}
                        --deploy ${{ steps.setup.outputs.DEPLOY_BRANCH }}
